
name: Docker Build and Deploy to EC2

on:
  push:
    branches:
      - main  

jobs:
  build-and-push:
    name: Build Docker Image and Push to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push Docker image to ECR
        run: |
          IMAGE_URI=${{ secrets.ECR_REPOSITORY }}:latest
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
  deploy:
    name: Deploy to EC2
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "🔐 Logging into AWS ECR"
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 241533115769.dkr.ecr.us-east-1.amazonaws.com

            echo "📂 Navigating to project directory"
            cd /home/ubuntu/prashant/recom || { echo '❌ Directory not found'; exit 1; }

            echo "🚀 Starting containers"
            docker compose up -d --build

            echo "✅ Deployment completed"
