name: Docker Build, Push & Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build-push-deploy:
    name: Build, Push to ECR & Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 3: Login to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Step 4: Build and Push Docker Image to ECR
      - name: Build & Push Docker Image to ECR
        run: |
          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)  # Get a unique image tag using commit SHA
          docker build -t $ECR_URI:$IMAGE_TAG -t $ECR_URI:latest .
          docker push $ECR_URI:$IMAGE_TAG
          docker push $ECR_URI:latest

      # Step 5: SSH and Deploy to EC2
      - name: SSH and Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Logging into ECR on EC2"
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 241533115769.dkr.ecr.us-east-1.amazonaws.com

            echo "Navigating to project directory"
            cd /home/ubuntu/prashant/transparency-labels 

            echo "Pulling latest image from ECR"
            docker compose pull  # Pull the latest image from ECR

            echo "Starting containers"
            docker compose up -d  # Start containers without rebuilding

            echo "Deployment successful"
