name: Docker Build, Push & Deploy to EC2 via SSM

on:
  push:
    branches:
      - master

jobs:
  build-push-deploy:
    name: Build, Push to ECR & Deploy via SSM
    runs-on: ubuntu-latest

    steps:
      # Step 5: Deploy via AWS SSM
      - name: Deploy using AWS SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceIds,Values=${{ secrets.EC2_INSTANCE_ID }}" \
            --comment "GitHub Actions deployment" \
            --parameters commands='[
              "echo Pulling latest code from Git",
              "cd ${{ secrets.PROJECT_DIR_PATH }}",
              "git pull origin master",
              "echo Logging into ECR",
              "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}",
              "echo Pulling latest image",
              "docker compose pull",
              "echo Starting containers",
              "docker compose up -d",
              "echo Deployment complete"
            ]' \
            --region ${{ secrets.AWS_REGION }} \
            --output text
